name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Root Dependencies
      run: npm install --legacy-peer-deps

    - name: Fix Vulnerabilities
      run: npm audit fix --force

    - name: Install Server Dependencies
      working-directory: ./server
      run: npm install --legacy-peer-deps

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build
